name: test-job

on: 
    push:
    pull_request:

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Date Setup (MM/DD/YYYY)
              id: date
              run: echo "today=$(date +'%m/%d/%Y')" >> "$GITHUB_OUTPUT"

            - name: Runtime-Enviornment(Node js 20)
              uses: actions/setup-node@v4
              with:
                 node-version: 20
                 cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name:  Run Unit Tests (Vitest)
              run: npm run test



